/** Audit-log vocabulary. New business events are added here as stages land. */
export const ActivityAction = {
  AGENCY_INITIALIZED: "agency.initialized",
  USER_INVITED: "user.invited",
  USER_INVITE_RESENT: "user.invite_resent",
  USER_INVITE_REVOKED: "user.invite_revoked",
  USER_ACTIVATED: "user.activated",
  USER_SUSPENDED: "user.suspended",
  USER_REACTIVATED: "user.reactivated",
  USER_DEACTIVATED: "user.deactivated",
  USER_ROLE_CHANGED: "user.role_changed",
  USER_PROFILE_UPDATED: "user.profile_updated",
  USER_PASSWORD_RESET: "user.password_reset",
  BRAND_CREATED: "brand.created",
  BRAND_UPDATED: "brand.updated",
  BRAND_ARCHIVED: "brand.archived",
  BRAND_REACTIVATED: "brand.reactivated",
  BRAND_PRIMARY_UPLOADER_CHANGED: "brand.primary_uploader_changed",
  MEMBERSHIP_ADDED: "membership.added",
  MEMBERSHIP_DEACTIVATED: "membership.deactivated",
  MEMBERSHIP_REACTIVATED: "membership.reactivated",
  MEMBERSHIP_ROLE_CHANGED: "membership.role_changed",
  CONTENT_CREATED: "content.created",
  CONTENT_UPDATED: "content.updated",
  CONTENT_STATUS_CHANGED: "content.status_changed",
  CONTENT_ARCHIVED: "content.archived",
  CONTENT_IDEA_ACCEPTED: "content.idea_accepted",
  CONTENT_IDEA_REJECTED: "content.idea_rejected",
  CONTENT_IDEA_CHANGES_REQUESTED: "content.idea_changes_requested",
  CONTENT_IDEA_RESUBMITTED: "content.idea_resubmitted",
  CONTENT_ROUTE_CHANGED: "content.route_changed",
  CONTENT_UPLOADER_OVERRIDE_CHANGED: "content.uploader_override_changed",
  TASK_CREATED: "production_task.created",
  TASK_ASSIGNED: "production_task.assigned",
  TASK_STATUS_CHANGED: "production_task.status_changed",
  VERSION_CREATED: "content_version.created",
  REFERENCE_CREATED: "reference.created",
  REFERENCE_UPDATED: "reference.updated",
  SHOOT_CREATED: "shoot.created",
  SHOOT_UPDATED: "shoot.updated",
  SHOOT_RESCHEDULED: "shoot.rescheduled",
  SHOOT_STARTED: "shoot.started",
  SHOOT_CREW_ASSIGNED: "shoot.crew_assigned",
  SHOOT_CREW_REMOVED: "shoot.crew_removed",
  SHOOT_CREW_STARTED: "shoot.crew_started",
  SHOOT_CREW_COMPLETED: "shoot.crew_completed",
  SHOOT_PARTIALLY_COMPLETED: "shoot.partially_completed",
  SHOOT_COMPLETED: "shoot.completed",
  SHOOT_CANCELLED: "shoot.cancelled",
  SHOOT_CONFLICT_OVERRIDE: "shoot.conflict_override",
  SHOOT_CONTENT_ADDED: "shoot.content_added",
  SHOOT_CONTENT_REMOVED: "shoot.content_removed",
  APPROVAL_SUBMITTED_INTERNAL: "approval.submitted_for_internal_review",
  APPROVAL_INTERNAL_APPROVED: "approval.internal_approved",
  APPROVAL_INTERNAL_CHANGES_REQUESTED: "approval.internal_changes_requested",
  APPROVAL_SUBMITTED_CLIENT: "approval.submitted_for_client_review",
  APPROVAL_CLIENT_APPROVED: "approval.client_approved",
  APPROVAL_CLIENT_CHANGES_REQUESTED: "approval.client_changes_requested",
  APPROVAL_CLIENT_RECORDED_BY_ADMIN: "approval.client_decision_recorded_by_admin",
  APPROVAL_REOPENED_FOR_CHANGES: "approval.reopened_for_changes",
  CONTENT_TARGET_PLATFORMS_CHANGED: "content.target_platforms_changed",
  POSTING_STARTED: "posting.started",
  POSTING_PLATFORM_POSTED: "posting.platform_posted",
  POSTING_RECORDED_BY_ADMIN: "posting.recorded_by_admin",
  POSTING_CORRECTED: "posting.corrected",
  POSTING_CANCELLED: "posting.cancelled",
  CONTENT_POSTED: "content.posted",
  CONTENT_COMPLETED: "content.completed",
  CONTENT_REVISION_STARTED: "content.post_publication_revision_started",
  EXPENSE_CREATED: "expense.created",
  EXPENSE_UPDATED: "expense.updated",
  EXPENSE_SUBMITTED: "expense.submitted",
  EXPENSE_WITHDRAWN: "expense.withdrawn",
  EXPENSE_APPROVED: "expense.approved",
  EXPENSE_REJECTED: "expense.rejected",
  MEDIA_UPLOADED: "asset.media_uploaded",
} as const;
export type ActivityAction = (typeof ActivityAction)[keyof typeof ActivityAction];
export const ACTIVITY_ACTIONS = Object.values(ActivityAction);

export const ActivityEntityKind = {
  AGENCY: "AGENCY",
  USER: "USER",
  BRAND: "BRAND",
  BRAND_MEMBERSHIP: "BRAND_MEMBERSHIP",
  CONTENT: "CONTENT",
  PRODUCTION_TASK: "PRODUCTION_TASK",
  CONTENT_VERSION: "CONTENT_VERSION",
  REFERENCE: "REFERENCE",
  SHOOT: "SHOOT",
  APPROVAL: "APPROVAL",
  POSTING: "POSTING",
  EXPENSE: "EXPENSE",
  ASSET: "ASSET",
} as const;
export type ActivityEntityKind = (typeof ActivityEntityKind)[keyof typeof ActivityEntityKind];
export const ACTIVITY_ENTITY_KINDS = Object.values(ActivityEntityKind);

/** Human wording for the content activity timeline (unknown actions fall back to a readable form). */
const ACTIVITY_LABEL: Partial<Record<ActivityAction, string>> = {
  "content.created": "Content created",
  "content.updated": "Details edited",
  "content.status_changed": "Status changed",
  "content.archived": "Archived",
  "content.idea_accepted": "Idea accepted",
  "content.idea_rejected": "Idea rejected",
  "content.idea_changes_requested": "Idea: changes requested",
  "content.route_changed": "Production route changed",
  "content.uploader_override_changed": "Uploader changed for this content",
  "content.target_platforms_changed": "Target platforms changed",
  "content.posted": "Posted on every required platform",
  "content.completed": "Completed",
  "content.post_publication_revision_started": "New revision started",
  "production_task.created": "Task created",
  "production_task.assigned": "Task assigned",
  "production_task.status_changed": "Task status changed",
  "content_version.created": "Version added",
  "approval.submitted_for_internal_review": "Submitted for internal review",
  "approval.internal_approved": "Internally approved",
  "approval.internal_changes_requested": "Internal changes requested",
  "approval.submitted_for_client_review": "Sent to the client",
  "approval.client_approved": "Client approved",
  "approval.client_changes_requested": "Client requested changes",
  "approval.client_decision_recorded_by_admin": "Client approval recorded by admin",
  "approval.reopened_for_changes": "Sent back for changes before posting",
  "posting.started": "Posting started",
  "posting.platform_posted": "Platform posted",
  "posting.recorded_by_admin": "Post recorded by admin",
  "posting.corrected": "Post corrected",
  "posting.cancelled": "Posting cancelled",
  "shoot.content_added": "Added to a shoot",
  "shoot.content_removed": "Removed from a shoot",
};
export function activityLabel(action: string): string {
  return ACTIVITY_LABEL[action as ActivityAction] ?? action.replace(/[._]/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}
